# This is a basic workflow to help you get started with Actions

name: CI
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!


  deploy_dev:
    runs-on: ubuntu-latest
    environment: 
      name: desenvolvimento
      url: 'thiagocsilva.com'
    needs: build  
    steps:
      - name: Run a one-line script
        run: echo Deploy DEV!

  deploy_hom:
    runs-on: ubuntu-latest
    environment: 
      name: hom
      url: 'thiagocsilva.com'
    needs: deploy_dev  
    steps:
      - name: Run a one-line script
        run: echo Deploy HOM!
        
  deploy_prod:
      runs-on: ubuntu-latest
      environment: 
        name: prod
        url: 'thiagocsilva.com'
      needs: build  
      steps:
        - name: Run a one-line script
          run: echo Deploy PROD!
